---
roles:
  - name: geerlingguy.node_exporter
    version: 2.1.0
  - name: geerlingguy.docker
    version: 7.4.1
  - name: artis3n.tailscale
    version: v4.5.0
  - name: robertdebock.collectd
    version: 3.1.7
collections:
  - community.general
  - victoriametrics.cluster
