---
# The VMs running on top of Proxmox
- name: Run apt update/upgrade/autoremove on the Ubuntu VMs
  hosts: "{{ hosts | default([])}}"
  become: true
  gather_facts: false
  tasks:
    - name: Run apt update/upgrade/autoremove
      ansible.builtin.apt:
        update_cache: true
        upgrade: true
        autoremove: true
