---
# The VMs running on top of Proxmox
- name: Update Other Ubuntu VMs (apt)
  hosts: 'other_vms'
  become: yes
  gather_facts: false
  tasks:
    - name: apt
      apt:
        update_cache: yes
        upgrade: yes
        autoremove: yes
