---
- name: Install Essential packages on the given servers
  hosts: '{{ vm_hosts | default("all")}}'
  become: true
  gather_facts: true
  tasks:
    - name: Install essential packages
      become: true
      ansible.builtin.apt:
        name:
          - htop
          - build-essential
          - net-tools
          - git
          - vim
          - curl
        state: present
        update_cache: true
    - name: Install starship
      ansible.builtin.shell:
        cmd: curl -sS https://starship.rs/install.sh | sh -s -- -y
      args:
        creates: /usr/local/bin/starship
    - name: Install fzf for the user
      become: false
      ansible.builtin.shell:
        cmd: >
          git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf &&
          ~/.fzf/install --all
      args:
        creates: "{{ ansible_user_dir }}/.fzf/bin/fzf"
    - name: Add starship init to .bashrc
      become: false
      ansible.builtin.lineinfile:
        path: "{{ ansible_user_dir }}/.bashrc"
        line: 'eval "$(starship init bash)"'
        create: true
      when:
        - ansible_user_shell is defined
        - ansible_user_shell.endswith('bash')
