---
# Using this role
# https://github.com/geerlingguy/ansible-role-node_exporter
- name: Install Node Exporter
  hosts: "{{ vm_hosts | default([])}}"
  become: true
  roles:
    - geerlingguy.node_exporter
