---
- name: Install Zsh on Proxmox servers
  hosts: 'proxmox'
  become: true
  gather_facts: false
  tasks:
    - name: Install zsh
      become: true  # become a superuser
      ansible.builtin.apt:
        name: zsh
        state: present
        update_cache: true
