---
- name: "Install Tailscale (but skip authentication)"
  hosts: '{{ vm_hosts | default("all")}}'
  gather_facts: true
  become: true
  roles:
    - role: artis3n.tailscale
      vars:
        tailscale_authkey: "{{ lookup('env', 'TAILSCALE_KEY') }}"
