---
- name: Install qemu-guest-agent package
  hosts: vms_on_proxmox
  become: true
  tasks:
    - name: Install qemu-guest-agent
      ansible.builtin.apt:
        name: qemu-guest-agent
        state: present
