---
- name: Update Oh My Zsh on all hosts
  hosts: all
  gather_facts: true
  tasks:
    - name: Check if Oh My Zsh is installed
      ansible.builtin.stat:
        path: "{{ ansible_env.HOME }}/.oh-my-zsh"
      register: omz_installed

    - name: Print Oh My Zsh installation status
      ansible.builtin.debug:
        msg: "Oh My Zsh is not installed."
      when: not omz_installed.stat.exists

    - name: "Run omz update"
      ansible.builtin.command: /bin/zsh -i -c 'omz update'
      changed_when: omz_installed.stat.exists
