---
name: lint
on: push
jobs:
  lint:
    name: Linting
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Install yamllint
        run: pip3 install yamllint
      - name: Lint code.
        run: |
          yamllint .
      - name: Install Ansible.
        run: pip3 install ansible-core
      - name: Install necessary dependencies
        run: ansible-galaxy install geerlingguy.node_exporter
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
