---
name: lint
on: push
jobs:
  lint:
    name: Linting
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Lint code.
        run: uv run --python 3.12 --with yamllint yamllint .
      - name: Install Ansible.
        run: pip3 install ansible-core
      - name: Install necessary dependencies
        run: |
          uv run --python 3.12 --with ansible-core \
            ansible-galaxy install geerlingguy.node_exporter
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
